/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui.br.com.servidor.projetologin;

import Gui.br.com.servidor.projetologin.ActionListeners.CadastrarCliente;
import Gui.br.com.servidor.projetologin.ActionListeners.PesquisarCliente;
import Gui.br.com.servidor.projetologin.ActionListeners.SalvarDadosCliente;
import br.ufpb.dcx.Mateus.*;

import javax.swing.*;
import java.io.IOException;

/**
 *
 * @author renil
 */
public class TelaPrinc extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrinc
     */
    public TelaPrinc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SistemaProvedorInternetMax sistema = new SistemaProvedorInternetMax();
        try {
            sistema.recuperaDados();
            JOptionPane.showMessageDialog(this, "Dados recuperados.");
        } catch (IOException e) {
            e.printStackTrace();
        }

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuPlano = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuEstoque = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        MenuSobre = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        JMenuItem salvarDados = new javax.swing.JMenuItem();
//        recuperaDados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("imgs/MaxConnectTela.png")); // NOI18N

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, Short.MAX_VALUE)  //1265
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, Short.MAX_VALUE) //805
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        MenuCliente.setText("Cliente");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new CadastrarCliente(sistema, this));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuCliente.add(jMenuItem1);

        jMenuItem2.setText("Alterar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuCliente.add(jMenuItem2);

        jMenuItem3.setText("Pesquisar");
        jMenuItem3.addActionListener(new PesquisarCliente(sistema, this));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuCliente.add(jMenuItem3);

        jMenuItem4.setText("Remover");
        MenuCliente.add(jMenuItem4);
        salvarDados.setText("Salvar dados do cliente.");
        salvarDados.addActionListener(new SalvarDadosCliente(sistema, this));
        MenuCliente.add(salvarDados);
        jMenuBar1.add(MenuCliente);

        MenuPlano.setText("Plano");

        jMenuItem5.setText("Cadastrar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuPlano.add(jMenuItem5);

        jMenuItem6.setText("Pesquisar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem6ActionPerformed(evt);
            }
        });
        MenuPlano.add(jMenuItem6);

        jMenuItem7.setText("Alterar");

        MenuPlano.add(jMenuItem7);

        jMenuBar1.add(MenuPlano);

        MenuEstoque.setText("Estoque");

        jMenuItem8.setText("Cadastrar");

        MenuEstoque.add(jMenuItem8);

        jMenuItem9.setText("Pesquisar");
        MenuEstoque.add(jMenuItem9);

        jMenuItem10.setText("Alterar");
        MenuEstoque.add(jMenuItem10);

        jMenuItem12.setText("Remover");
        MenuEstoque.add(jMenuItem12);

        jMenuBar1.add(MenuEstoque);

        MenuSobre.setText("Sobre");

        jMenuItem11.setText("Sair");
//        jMenuItem11.addActionListener(new );
        MenuSobre.add(jMenuItem11);

        jMenuBar1.add(MenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();


    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenu MenuEstoque;
    private javax.swing.JMenu MenuPlano;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

//               try {
//Cliente c = new Cliente(jLabel2.getText(), jLabel3.getText(), jLabel4.getText(), jLabel5.getText(),
//        jLabel6.getText(), jLabel7.getText(), jLabel10.getText(), jLabel11.getText(), Plano.planosPadrao.get(jLabel12.getText()));
//                    sistema.cadastrarCliente(c);
//                } catch (
//ClienteJaCadastradoException e) {
//        JOptionPane.showMessageDialog();
//                }
